### ISSUE TITLE
Support `RENAME` in migrations

### ISSUE THREAD

**Issue by whatyouhide** [vinniefranco/exandra#32]
Currently, for this migration:

```elixir
rename table("my_table"), :old_name, to: :new_name
```

You get this:

```
** (FunctionClauseError) no function clause matching in Exandra.Connection.execute_ddl/1    
    
    The following arguments were given to Exandra.Connection.execute_ddl/1:
    
        # 1
        {:rename, %Ecto.Migration.Table{name: "cursors", prefix: nil, comment: nil, primary_key: true, engine: nil, options: nil}, :source_type, :resource_type}
    
    Attempted function clauses (showing 9 out of 9):
    
        def execute_ddl({command, %Ecto.Migration.Table{} = table, columns}) when command === :create or command === :create_if_not_exists
        def execute_ddl({:alter, %Ecto.Migration.Table{} = table, columns})
        def execute_ddl({command, %Ecto.Migration.Table{} = table, _}) when command === :drop or command === :drop_if_exists
        def execute_ddl({_command, %Ecto.Migration.Constraint{}, _})
        def execute_ddl({_command, %Ecto.Migration.Constraint{}})
        def execute_ddl({command, %Ecto.Migration.Index{} = index}) when command === :create or command === :create_if_not_exists
        def execute_ddl({command, %Ecto.Migration.Index{} = index, :restrict}) when command === :drop or command === :drop_if_exists
        def execute_ddl({command, %Ecto.Migration.Index{}, :cascade}) when command === :drop or command === :drop_if_exists
        def execute_ddl(string) when is_binary(string)
    
    (exandra 0.6.5) lib/exandra/connection.ex:645: Exandra.Connection.execute_ddl/1
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1003: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
    (elixir 1.15.2) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (stdlib 5.0.2) timer.erl:270: :timer.tc/2
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:362: Ecto.Migrator.attempt/8
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:283: anonymous fn/5 in Ecto.Migrator.do_up/5
```

**Comment by vinniefranco** [comment]
renames have been added in the latest release!
