### ISSUE TITLE
Cannot create schema_migrations

### ISSUE THREAD

**Issue by pustserg** [vinniefranco/exandra#36]
**Describe the bug**
I added the exandra to the deps `{:exandra, "~> 0.6"}`
Then I made a repo with config 
```
defmodule Chats.XandraRepo do
  use Ecto.Repo,
    otp_app: :chats,
    adapter: Exandra
end
```
And generated a migration.

But when I run `mix ecto.migrate` I get the following error
```
[error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:
```

I see my keyspace in `cqlsh` so the database definitely exists
What can I do to fix it?

**Comment by whatyouhide** [comment]
What version of Exandra are you using? You specified `~> 0.6` on the issue, but the latest version is `0.7.5`. What's the version in your `mix.lock`?

Also, is that the only error you get? IIRC there's more context to this.

**Comment by pustserg** [comment]
`"exandra": {:hex, :exandra, "0.6.5", "bb13655271cf28bdff1daa9f7516c57f20fd5c8d08c44c058eb28cb3bbb867ce", [:mix], [{:decimal, "~> 1.6 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}`

I'll try to upgrade exandra

**Comment by pustserg** [comment]
Unfortunately upgrade did not help

```
15:36:48.383 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:

    config :chats, Chats.XandraRepo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (Xandra.ConnectionError) action "checkout from cluster #PID<0.212.0>" failed with reason: not connected to any of the nodes
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:756: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:564: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:433: Ecto.Migrator.run/4
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    (ecto_sql 3.10.2) lib/mix/tasks/ecto.migrate.ex:141: anonymous fn/5 in Mix.Tasks.Ecto.Migrate.run/2
    ```
    
    Looks like there is no connection, but `mix ecto.create` creates keyspace correctly 🤷

**Comment by vinniefranco** [comment]
@pustserg what does your config look like? What env are you getting that error in?

**Comment by whatyouhide** [comment]
> action "checkout from cluster #PID<0.212.0>" failed with reason: not connected to any of the nodes

@pustserg also, this points you to the fact that the issue is that you cannot connect to the database, not that there is an actual issue creating the `schema_migrations` table.

**Comment by pustserg** [comment]
@vinniefranco it's development env

dev.exs

```
config :chats, Chats.XandraRepo,
  hostname: "127.0.0.1",
  port: "9042",
  keyspace: "chats_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10
```
I tried with a localhost and without port option, result is the same

`xandra_repo.ex`
```
defmodule Chats.XandraRepo do
  use Ecto.Repo,
    otp_app: :chats,
    adapter: Exandra
end
```

**Comment by pustserg** [comment]
> > action "checkout from cluster #PID<0.212.0>" failed with reason: not connected to any of the nodes
> 
> @pustserg also, this points you to the fact that the issue is that you cannot connect to the database, not that there is an actual issue creating the `schema_migrations` table.

I see it, but I'm wondered that `mix ecto.create` creates keyspace in the cassandra

**Comment by whatyouhide** [comment]
@pustserg can you try to pass `sync_connect: timeout` to the config? Something like:

```elixir
config :chats, Chats.XandraRepo,
  # ...,
  sync_connect: 5000 # Or any timeout you prefer
```

**Comment by pustserg** [comment]
@whatyouhide checked. Error is the same :(

**Comment by whatyouhide** [comment]
Can you run this and paste all the output (using the config above + `sync_connect`:

```
mix ecto.drop
mix ecto.create
mix ecto.migrate
```

**Comment by pustserg** [comment]
@whatyouhide 

```
➜  chats git:(main) ✗ mix ecto.drop
The database for Chats.XandraRepo has been dropped
The database for Chats.PostgresRepo has been dropped
➜  chats git:(main) ✗ mix ecto.create
The database for Chats.XandraRepo has been created
The database for Chats.PostgresRepo has been created

➜  chats git:(main) ✗ mix ecto.migrate

10:26:03.016 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:

    config :chats, Chats.XandraRepo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (Xandra.ConnectionError) action "checkout from cluster #PID<0.212.0>" failed with reason: not connected to any of the nodes
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:756: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:564: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:433: Ecto.Migrator.run/4
    (ecto_sql 3.10.2) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    (ecto_sql 3.10.2) lib/mix/tasks/ecto.migrate.ex:141: anonymous fn/5 in Mix.Tasks.Ecto.Migrate.run/2
```

<img width="1516" alt="image" src="https://github.com/vinniefranco/exandra/assets/1678459/dfef1f3a-8ad2-404c-b0c8-4c82a8b97d0b">

**Comment by whatyouhide** [comment]
Can you try using `:nodes` in the config?

```elixir
config :chats, Chats.XandraRepo,
  nodes: ["127.0.0.1:9042"],
  keyspace: "chats_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  sync_connect: 5000
```

and make sure you're on Exandra 0.8.1?
