### ISSUE TITLE
Error creating table `Missing ')'`

### ISSUE THREAD

**Issue by restlessronin** [vinniefranco/exandra#54]
### Discussed in https://github.com/vinniefranco/exandra/discussions/53

<div type='discussions-op-text'>

<sup>Originally posted by **restlessronin** March 28, 2024</sup>
I am successfully running migrations now. One of my migrations is giving me the following
```
11:32:40.004 [info] create table messages
** (Xandra.Error) line 1:32 : Missing ')'
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1161: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.11.1) lib/ecto/migration/runner.ex:348: Ecto.Migration.Runner.log_and_execute_ddl/3
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (stdlib 5.2) timer.erl:270: :timer.tc/2
    (ecto_sql 3.11.1) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:365: Ecto.Migrator.attempt/8
```
Here is the migration being attempted
```elixir
defmodule Mai.Repo.Migrations.CreateMessages do
  use Ecto.Migration

  def change do
    create table(:messages, primary_key: false) do
      add(:id, :binary_id, primary_key: true)
      add(:order, :int)
      add(:role, :string)
      add(:content, :string)

      add(:chat_id, :binary_id)
      add(:original_message_id, :binary_id)

      timestamps()
    end
  end
end
```
i changed from `:integer` to `:int`, but that didn't seem to matter.

UPDATE. When I remove the `:order` field, however, the migration succeeds.</div>

**Comment by vinniefranco** [comment]
order is a reserved keyword https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/keywords_r.html

**Comment by vinniefranco** [comment]
No worries, I run into this all the time with `type` I _always_ want a type col and end up having to name it `kind` 😿
